apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-svc-3802
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/auth-svc-3802
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
